### PR TITLE
hoc2023: prettier JS files

### PR DESCRIPTION
**Pull request by breville**
This updates the formatting of all JS files in this repo, in preparation for additional updates for hoc2023.

### CODE REVIEW

**Review by bencodeorg — APPROVED** [review]

**Review by sanchitmalhotra126 — APPROVED** [review]

**Review by fisher-alice — APPROVED** [review]
Thanks for prepping for the upcoming changes. I am curious - were you able to make all the 'prettier' changes automatically? I see you added the configuration to `.prettierrc.js` after you made the file updates.

**Comment by breville** [comment]
> Thanks for prepping for the upcoming changes. I am curious - were you able to make all the 'prettier' changes automatically? I see you added the configuration to `.prettierrc.js` after you made the file updates.

I applied these in an editor, one file at a time, but presumably there is a way to do this by batch in the command line.  I had the `prettierrc.js` file there the whole time, but didn't commit it until later.

**Comment by fisher-alice** [comment]
> > Thanks for prepping for the upcoming changes. I am curious - were you able to make all the 'prettier' changes automatically? I see you added the configuration to `.prettierrc.js` after you made the file updates.
> 
> I applied these in an editor, one file at a time, but presumably there is a way to do this by batch in the command line. I had the `prettierrc.js` file there the whole time, but didn't commit it until later.

Oh gotcha - thanks!

**Comment by fisher-alice** [comment]
General question - will we bump up the version after all the hoc updates?

**Comment by breville** [comment]
> General question - will we bump up the version after all the hoc updates?

We will bump the version each time we have a new build that we want to be consumed by our main repo, which I think should be done regularly once we have momentum.

**Comment by breville** [comment]
I went ahead and did the other JS files in the repo too.

**Pull request merged**
